# Generated by Django 4.2.4 on 2023-08-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='associated_habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_pleasurable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker_app.habit', verbose_name='связанная привычка'),
        ),
    ]
